<a href="https://colab.research.google.com/github/Wangari-Kariuki/Program-interest-vs-graduation-rate/blob/main/final_project_report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part 1: Exploring data of enrollment students from 2017 to 2021

The Objective of this projct is to examine whether there is a correlation between  student's major choices and their probability of switching majors. Addtionally we will track the graduation status of studentswho switch majors.
We will do this by keeping the following qestions in mind during the  analysis
1. What students have switched from one major to another?
2. What majors do most students switch to and from?
3. What is the graduations status of students who switch majors?

Visualizations may inlude:
1. Time trend of students from listing major options, dropping, switching and  finally graduating.
2. Bar graph or histogram of different majors and number of students who express interest of them.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/drive/MyDrive/CS215-Spring-ESTHER/Projects/Final Project/Enrolled Applicants fall 2017-2021.xlsx')
df.columns

Index(['Student ID', 'Start Term', 'All Academic Interests',
       'Primary Academic Interest'],
      dtype='object')

In [ ]:
df.info()
df.count()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2010 entries, 0 to 2009
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student ID                 2010 non-null   int64
 1   Start Term                 2010 non-null   object
 2   All Academic Interests     2010 non-null   object
 3   Primary Academic Interest  1939 non-null   object
dtypes: int64(1), object(3)
memory usage: 62.9+ KB

Student ID                   2010
Start Term                   2010
All Academic Interests       2010
Primary Academic Interest    1939
dtype: int64

In [ ]:
noPrimaryAcademicInterest = df.loc[df['Primary Academic Interest'] == 'Undecided']
noPrimaryAcademicInterest  #primary academic interest not stated
print(f"Number of students with no listed primary academic interest: {len(noPrimaryAcademicInterest)}")

Number of students with no listed primary academic interest: 134

we could match this students allong with their graduation statuses.

In [ ]:
# @title
noInterest = df.loc[df['All Academic Interests']== 'Undecided']
noInterest #students with no stated academic interests
print(f" Number of students with no listed secondary academic interests: {len(noInterest)}")

 Number of students with no listed secondary academic interests: 51

we could match this students allong with their graduation statuses.

In [ ]:
#now let's see how many students have neither primary nor secondary academic interests
no_aca_int = df[(df['All Academic Interests'] == 'Undecided') & (df['Primary Academic Interest'] == 'Undecided')]
print(f"Number of students with no stated academic interests in either categories: {len(no_aca_int)}")

Number of students with no stated academic interests in either categories: 29

In [ ]:
#we drop rows undecided students
new_df = df.drop(no_aca_int.index)
#new_df.info()
#we still have null values in primary academics interest columns
new_df['All Academic Interests'].head(3)
new_df.dropna()
empty = len(new_df['Primary Academic Interest'].isnull())
print(empty)
new_df['Primary Academic Interest'].head()
new_df.info()

1981
<class 'pandas.core.frame.DataFrame'>
Index: 1981 entries, 0 to 2009
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student ID                 1981 non-null   int64
 1   Start Term                 1981 non-null   object
 2   All Academic Interests     1981 non-null   object
 3   Primary Academic Interest  1910 non-null   object
dtypes: int64(1), object(3)
memory usage: 77.4+ KB

In [ ]:
#let's examine  the all secondary  academic interest
#convert the items in the column form objects to strings then to lists

# Restore 'All Academic Interests' in new_df to its original string format from df
# This step is crucial if the cell was run multiple times and the column became garbled
new_df['All Academic Interests'] = df.loc[new_df.index, 'All Academic Interests']

# Ensure all entries are strings before splitting
new_df['All Academic Interests'] = new_df['All Academic Interests'].astype(str)
# Replace specific 'Nan' string if it exists after conversion; also consider 'nan' (lowercase) for np.nan
new_df['All Academic Interests'] = new_df['All Academic Interests'].replace('Nan', '')
# Now split the strings and strip whitespace from each item, filtering out any empty strings
new_df['All Academic Interests'] = new_df['All Academic Interests'].str.split(',').apply(lambda x: [item.strip() for item in x if item.strip()])
print(type(new_df['All Academic Interests'].iloc[0])) # we've successfully converted each item in our series into a list

<class 'list'>

In [ ]:

new_df['count'] = new_df['All Academic Interests'].str.len()
new_df[['count', 'All Academic Interests']]
print(f"Average number of programs students show secondary  interest in : {new_df['count'].mean()}")

Average number of programs students show secondary  interest in : 4.108026249369005

In [ ]:
#we split the students according to those with above average number of interests and those with below average number of s. interests
many_interests = new_df.loc[new_df['count'] >= 4]
many_interests
print(f"{len(many_interests)} students have more interests than average")
#what is the modal number of s. interests
print(f"most students list {len(new_df['count'].mode())} intersts ") #positively skewed variance of number of interests per student

1041 students have more interests than average
most students list 1 intersts

In [ ]:
few_interests =  new_df.loc[new_df['count'] < 4]
print(f"{len(few_interests)} students have less interests than average")

940 students have less interests than average

todo: Stem and leaf plot or a line graph representing the nature of the data

In [ ]:
import plotly.express as px

# Create the histogram using Plotly Express
fig = px.histogram(new_df, x='count', nbins=20)

# Update layout for aesthetics similar to original matplotlib plot
fig.update_layout(
    title_text="Distribution of students within a range of 1 to 20 academic interests",
    xaxis_title_text="number of interest",
    yaxis_title_text="students",
    xaxis_range=[0, 20],
    yaxis_range=[0, 700],
    bargap=0.01 # Adjust for edgecolor effect, creating small gaps between bars
)

# Save the interactive HTML plot
fig.write_html("first_visuali.html")

# Display the plot
fig.show()

# Part 2
Merging with graduation data

In [ ]:
grad_df = pd.read_csv('/content/drive/MyDrive/CS215-Spring-ESTHER/Projects/Final Project/Enrolled Applicants fall 2017-2021.xlsx - Declared Majors.csv')
grad_df.info()
grad_df.head(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4444 entries, 0 to 4443
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student ID                 4444 non-null   int64
 1   Student Status             4444 non-null   object
 2   Start Term                 4444 non-null   object
 3   Program Code               4444 non-null   object
 4   Program Status             4431 non-null   object
 5   Prog Add Date              4444 non-null   object
 6   Prog Status Date           4444 non-null   object
 7   Majors at Graduation       3554 non-null   object
 8   Currently Declared Majors  153 non-null    object
dtypes: int64(1), object(8)
memory usage: 312.6+ KB

,Student ID,Student Status,Start Term,Program Code,Program Status,Prog Add Date,Prog Status Date,Majors at Graduation,Currently Declared Majors
0,2649639,Graduated,2017FA,UNDC,Declared,05/05/2017,01/18/2019,THTR,NaN
1,2649639,Graduated,2017FA,BA.THTR,Graduated,01/18/2019,08/27/2021,THTR,NaN
2,5423674,Withdrawn,2017FA,UNDC,Withdrawn,02/19/2003,06/01/2018,NaN,NaN
3,7077890,Graduated,2020FA,UNDC,Declared,08/24/2020,11/12/2020,SOC,NaN

In [ ]:
#let's se how many students withdrew
withdrawn = grad_df.loc[grad_df['Student Status'] == "Withdrawn"]
withdrawn.info()
print(f"{len(withdrawn)} students withdrew  within 2017 and 2021 academic years ")

<class 'pandas.core.frame.DataFrame'>
Index: 737 entries, 2 to 4441
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student ID                 737 non-null    int64
 1   Student Status             737 non-null    object
 2   Start Term                 737 non-null    object
 3   Program Code               737 non-null    object
 4   Program Status             734 non-null    object
 5   Prog Add Date              737 non-null    object
 6   Prog Status Date           737 non-null    object
 7   Majors at Graduation       0 non-null      object
 8   Currently Declared Majors  0 non-null      object
dtypes: int64(1), object(8)
memory usage: 57.6+ KB
737 students withdrew  within 2017 and 2021 academic years

In [ ]:
grad_df = grad_df.drop(withdrawn.index)
grad_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3707 entries, 0 to 4443
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student ID                 3707 non-null   int64
 1   Student Status             3707 non-null   object
 2   Start Term                 3707 non-null   object
 3   Program Code               3707 non-null   object
 4   Program Status             3697 non-null   object
 5   Prog Add Date              3707 non-null   object
 6   Prog Status Date           3707 non-null   object
 7   Majors at Graduation       3554 non-null   object
 8   Currently Declared Majors  153 non-null    object
dtypes: int64(1), object(8)
memory usage: 289.6+ KB

In [ ]:
#now we ma=erge the grad_df with the interests df by matching the student ids
#first let's check for duplicates in our second df

dups_count = grad_df.duplicated(subset=['Student ID'], keep='last').sum()
dups_count

#our data contains two sets of information fro each student, first is when they declared their major and second is when they withdraw so we separate the two sets of information into two datasets
declared = grad_df.drop_duplicates(subset=['Student ID'], keep='last')
declared.info()
len(declared['Program Status'] == "Withdrawn")

<class 'pandas.core.frame.DataFrame'>
Index: 1717 entries, 1 to 4443
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student ID                 1717 non-null   int64
 1   Student Status             1717 non-null   object
 2   Start Term                 1717 non-null   object
 3   Program Code               1717 non-null   object
 4   Program Status             1716 non-null   object
 5   Prog Add Date              1717 non-null   object
 6   Prog Status Date           1717 non-null   object
 7   Majors at Graduation       1648 non-null   object
 8   Currently Declared Majors  69 non-null     object
dtypes: int64(1), object(8)
memory usage: 134.1+ KB

1717

In [ ]:
int_dec = new_df.merge(declared, on = "Student ID", how= "left")
int_dec.info()
w_ids = withdrawn['Student ID']
#now we remove major interests information about students who withdrew from our combined df we have their ids recorded in df withdrawn
int_dec = int_dec[~int_dec['Student ID'].isin(w_ids)]
int_dec.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1981 entries, 0 to 1980
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student ID                 1981 non-null   int64
 1   Start Term_x               1981 non-null   object
 2   All Academic Interests     1981 non-null   object
 3   Primary Academic Interest  1910 non-null   object
 4   count                      1981 non-null   int64
 5   Student Status             1606 non-null   object
 6   Start Term_y               1606 non-null   object
 7   Program Code               1606 non-null   object
 8   Program Status             1605 non-null   object
 9   Prog Add Date              1606 non-null   object
 10  Prog Status Date           1606 non-null   object
 11  Majors at Graduation       1540 non-null   object
 12  Currently Declared Majors  66 non-null     object
dtypes: int64(2), object(11)
memory usage: 201.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1606 entries, 0 to 1980
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student ID                 1606 non-null   int64
 1   Start Term_x               1606 non-null   object
 2   All Academic Interests     1606 non-null   object
 3   Primary Academic Interest  1551 non-null   object
 4   count                      1606 non-null   int64
 5   Student Status             1606 non-null   object
 6   Start Term_y               1606 non-null   object
 7   Program Code               1606 non-null   object
 8   Program Status             1605 non-null   object
 9   Prog Add Date              1606 non-null   object
 10  Prog Status Date           1606 non-null   object
 11  Majors at Graduation       1540 non-null   object
 12  Currently Declared Majors  66 non-null     object
dtypes: int64(2), object(11)
memory usage: 175.7+ KB

# Part 3

Here it gets even more fun!
we'll compare the program codes  with the primary ac interest column. to do that we might need to create a functions that first defines the subjects that each program code entails.
here i am required to do  a mapping or matching task

In [ ]:
program_codes = pd.read_csv('/content/drive/MyDrive/CS215-Spring-ESTHER/Projects/Final Project/Enrolled Applicants fall 2017-2021.xlsx - Program Codes and Titles.csv')
type(program_codes['Program Title'].iloc[0])
program_codes['Program Title'].iloc[0]
type(int_dec['All Academic Interests'].iloc[0][0])
type(program_codes['Program Title'].iloc[0])
#int_dec.columns

str

In [ ]:
#we need some normalization
import re
def normalize(text):
  text = text.lower()
  text = re.sub(r"[^a-z0-9\s]", "", text) # remove punctuations
  text = re.sub(r"\s+", " ", text).strip() #fix spacing
  return text

program_codes['normalized_titles'] = program_codes['Program Title'].apply(normalize)
int_dec['normalized_interests'] = int_dec['All Academic Interests'].apply(lambda x: [normalize(interest) for interest in x])

In [ ]:
# # Create mapping dictionary once
interests = int_dec['All Academic Interests']
program_map = dict(
    zip(
        program_codes['normalized_titles'],
        program_codes['Program Code']
    )
)

# Map interests to codes
# int_dec['interest codes'] = int_dec[
#     'normalized_interests'
# ].apply(
#     lambda interests: [
#         program_map[interest]
#         for interest in interests
#         if interest in program_map
#     ]
# )

# int_dec[['normalized_interests', 'interest codes']]

In [ ]:
# think about clustering
# next step : what kind of clusters do I want? - in type of major, number of program intesrests, graduation program,
# what is the correlataion all about?

In [ ]:
# Install fuzzywuzzy library for fuzzy string matching
#why I chose this library:
#Allows to match the subjects despite the inconsistent naming order compared to the program code titles

!pip install fuzzywuzzy
!pip install python-Levenshtein

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0
Collecting python-Levenshtein
  Downloading python_levenshtein-0.27.3-py3-none-any.whl.metadata (3.9 kB)
Collecting Levenshtein==0.27.3 (from python-Levenshtein)
  Downloading levenshtein-0.27.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein==0.27.3->python-Levenshtein)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading python_levenshtein-0.27.3-py3-none-any.whl (9.5 kB)
Downloading levenshtein-0.27.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (153 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.3/153.3 kB 2.2 MB/s eta 0:00:00
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 26.2 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, Levenshtein, python-Levenshtein
Successfully installed Levenshtein-0.27.3 python-Levenshtein-0.27.3 rapidfuzz-3.14.5

In [ ]:
from fuzzywuzzy import process

def fuzzy_match_interest_to_code(interests_list, program_map, threshold=80):
    matched_codes = []
    for interest in interests_list:
        # Find the best matching program title for the given interest
        # using fuzzy matching. process.extractOne returns (match, score)
        match = process.extractOne(interest, program_map.keys(), score_cutoff=threshold)
        if match:
            # If a match is found above the threshold, add its corresponding code
            matched_codes.append(program_map[match[0]])
    return list(set(matched_codes)) # Return unique codes

# Apply the fuzzy matching function to create new 'fuzzy interest codes'
int_dec['fuzzy_interest_codes'] = int_dec['normalized_interests'].apply(
    lambda x: fuzzy_match_interest_to_code(x, program_map)
)

# Display the results with both normalized interests and the new fuzzy codes
int_dec[['normalized_interests',  'fuzzy_interest_codes', 'Program Code']]
type(int_dec['fuzzy_interest_codes'].iloc[0])

list

In [ ]:
#removing the first two characters BA in Program codes
int_dec['Program Code'] = int_dec['Program Code'].str.strip('BA.')
int_dec[['normalized_interests',  'fuzzy_interest_codes', 'Program Code']].head(5)

,normalized_interests,fuzzy_interest_codes,Program Code
0,"[biochemistry biophysics molecular biology, en...","[BB.PE, AR.EN, BBMB]",PH.EN
1,"[politics, prelaw, undecided]",[POL],SOC
2,"[anthropology, biology, computer science, econ...","[REL, CS, PSYC, ANTH, IRES, PHIL, BIOL, ECON, ...",PSYC
3,"[anthropology, art history, economics, environ...","[ANTH, AR.EN, PHIL, ARTH, ECON]",ECON
4,"[anthropology, english, environmental studies,...","[ANTH, HIST, AR.EN, ENGL, JPNS]",NTH

In [ ]:
#now w e compare the declard  majors with the intial interests
#if dec major is in interest list, return true

interest_codes = int_dec['fuzzy_interest_codes'].values
declared = int_dec['Program Code']